# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReCoffee', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=20)),
                ('shop_name', models.CharField(max_length=20)),
            ],
        ),
    ]
