# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 23:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ReCoffee', '0005_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='f_id',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='shop_name',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='username',
        ),
        migrations.AddField(
            model_name='favorite',
            name='shop_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ReCoffee.ShopProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
